logging:
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: dev

  rabbitmq:
    host: localhost
    port: 5673
    username: lurui04
    password: Lurui_123456
    virtual-host: test
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual

  redis:
    database: 0
    lettuce:
      shutdown-timeout: 1000ms
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379

  #邮箱smtp相关配置
  mail:
    host: smtp.163.com
    port: 25
    username: luruigx08@163.com
    password: lurui123456
    protocol: smtp
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true




